openapi: 3.0.0
info:
  title: httpmock-query-array
  version: "0.0.0"
paths:
  /widgets:
    get:
      operationId: listWidgets
      parameters:
        - name: tags
          in: query
          required: true
          schema:
            type: array
            items:
              type: string
      responses:
        "204":
          description: no-content
