openapi: 3.0.0
info:
  description: Minimal API for testing parameter overrides
  title: Parameter override test
  version: v1
paths:
  "/bazzz":
    get:
      operationId: "bazooka"
      responses:
        "200":
          description: return some JSON string
          content:
            "application/json":
              schema:
                type: string
  "/foo/bar":
    get:
      # NOTE: no operation_id is set
      responses:
        "200":
          description: return some JSON string
          content:
            "application/json":
              schema:
                type: string
    post:
      # NOTE: no operation_id is set
      responses:
        "200":
          description: return some JSON string
          content:
            "application/json":
              schema:
                type: string
  "/foo.bar":
    get:
      # NOTE: no operation_id is set, however, the path will create a name collision
      # with GET /foo/bar
      responses:
        "200":
          description: return some JSON string
          content:
            "application/json":
              schema:
                type: string
